apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bulk-import-1776119591899
  annotations:
    github.com/project-slug: cloud-eda/bulk-import-1776119591899
spec:
  type: other
  lifecycle: unknown
  owner: user:default/test1
